### ISSUE TITLE
[realtime] Initialize and instantiate

### ISSUE THREAD

**Issue by kosssi** [cozy/cozy-libs#10]
The lib need to be instanciated and/or initialized to pass `url` and `token` to it, to avoid passing a config object to every call.

If we create an init function, we should write a reset function, because on mobile application we can unlink account.

All discussion on cozy-realtime repository:

---

gregorylegarec:

Thanks for removing cozy-client-js 🔥.

I feel that it's a little bit constraining to pass url and token at every subscribe call. May be we could initialize the realtime once as we do for the other cozy clients. something like :

```
realtime.init(url, token)
// Maybe we should instantiate it ?
// ... later
const subscription = realtime.subscribe('io.cozy.files')
```

What do you think ?

----

sebn:

> I feel that it's a little bit constraining to pass url and token at every subscribe call. May be we could initialize the realtime once as we do for the other cozy clients.

👍 `url` and `token` always _travel_ together, so they should probably be part of the same _config_ object, so we may reuse it, don't need to remember params order, and don't need to change function calls in case _config_ gets a new field.

Although I would prefer one of the following solutions:

1. Just pass the config objet to function calls, e.g. `realtime.subscribe(config, 'io.cozy.files')` (may be a first, easier to implement step)
2. Instanciate the realtime, e.g. `const realtime = Realtime.init()`, so consumer code doesn't need to know whether the result is built using a class or a closure. Module vs variable names always bother me in js, hence the capital R, but any other name would be fine by me. (probably out of the scope of this PR, so we may introduce it in a subsequent one)

In both case, we don't expose functions until they can actually be used so we don't get unexpected errors when calling them (a designer once gave me this example: "Tea or coffee? Oh sorry we don't have any of them...").

**Comment by ptbrowne** [comment]
+1 for initting realtime.

> In both case, we don't expose functions until they can actually be used so we don't get unexpected errors when calling them (a designer once gave me this example: "Tea or coffee? Oh sorry we don't have any of them...").

I am not sure I agree with this. If you do not expose the methods and try to call subscribe you will have

```
> realtime.subscribe()
undefined is not a function
```

IMHO, this is not as useful as

```
> realtime.subscribe()
Error: Realtime should be initialized with a token and URL before being used. Perhaps have you forgotten the `realtime.init({ token, url })` call ?
```

**Comment by sebn** [comment]
> I think cozy-client-js does not have its method exposed until exposition, and it was difficult for me to know where the bug was when I called the methods and they were not available.

@ptbrowne +1, I can't find my original comment, but I believe I was not suggesting some `object.init()` method that would have a side effect on `object` (i.e. magically adding some methods to it). If I remember correctly, it was more like `something = SomeModule.init() // then do what you want with something`, which I actually prefered to `something = new SomeClass()` (whether or not we're instanciating an object can be seen as an implementation detail).

**Comment by sebn** [comment]
Oh, just found my original message above, I was still looking for the `cozy-realtime` repo :)

**Comment by ptbrowne** [comment]
@sebn Ah ok I understand better. Yes I agree that having a half-baked object is not very useful.

> something = SomeModule.init() // then do what you want with something, which I actually prefered to something = new SomeClass() 

By reading `SomeModule.init()`, I have the impression that you are initializing the whole module, as a singleton. I find it clearer with a `new` that you will get a different instance at each time. It is effectively an implementation detail but since it has an effect on the external API, I think we should choose the clearer option, using the semantics of the language ;)

**Comment by sebn** [comment]
Agreed, `SomeModule.init()` is confusing. But maybe it may be just a naming issue, e.g. `SomeModule.buildSomething()`. And in case you want to instanciate a different class in two different contexts (dev/prod, node/browser...), you wouldn't have to change user code with a function.

**Comment by sebn** [comment]
Trying to summarize:

1. Should we initialize (i.e. mutate) the module object or instanciate a new object? From what I understood, I (@sebn), @ptbrowne and @drazik prefer instanciating a new object. What about others?
2. If we decide to instanciate a new object, should we make it explicit or wrap it into a factory function? @ptbrowne and @drazik prefers making it explicit, @sebn prefers using a factory function (but it's not a blocker for me so unless somebody else feels bad about it, let's go with `new Something()`)
3. If we decide to initialize the new object, would `realtime.init()` and `realtime.reset()` be fine?

**Comment by ptbrowne** [comment]
Dans Banks, voici comment on initialise les intents.

https://github.com/cozy/cozy-banks/blob/141587ae2af4a9d48372aa8e1ad37cb527ca167d/src/ducks/client/index.js#L15

Je verrais bien 

```js
client.registerPlugin(new Intent())
```

et qu'ensuite on puisse faire 

```
client.intents.start()
```

**Comment by kosssi** [comment]
Je pense que ça vaudrait le coup de cacher l’instanciation dans cozy client:

```
const cozyClient = new CozyClient({ ... })
cozyClient.intents.start()
```

**Comment by ptbrowne** [comment]
J'ai pas compris kosssi, tu ferais qqchose comme : 

```
const cozyClient = new CozyClient({ plugins: [Intent] })
```

?

Dans ce cas le soucis, cest comment tu donner les options.

Option 1, à la eslint : 

```
const cozyclient = new CozyClient({ plugins: [[Intent, { intentOption: true }]] })
```

Option 2, à la webpack: 

```
const cozclient = new CozyClient({
   plugins: [
   ]
})

// -- chez le plugin Intent
class IntentPlugin {
  onRegister(client) {
    this.token = client.token
  }
}
```

Donc dans l'option 1, Intent est instancié par le client, dans l'option 2, le plugin délaie son initialisation à lorsqu'il est recu par le client.

L'option 2 me parait un peu plus flexible sachant qu'on peut avoir besoin des méthodes de cycle de vie (onLogin, onLogout) pour les plugins à d'autres endroits.

**Comment by kosssi** [comment]
Pour l'instant les objets `Intents` s'initialisent seulement avec un client [voir ici](https://github.com/cozy/cozy-libs/blob/master/packages/interapp/src/intents.js#L7). Je vois pas encore l'interet de lui passer des options.

Pour cozy-realtime je voyais bien aussi l'initialiser seulement avec cozyClient et donc le faire automatiquement dans cozyClient.

```
const cozyclient = new CozyClient()
cozyClient.intents.start()
const subscription = await cozyClient.realtime.subscribeAll('io.mocks.mydocs')
```

**Comment by ptbrowne** [comment]
Si on initialise directement dans cozy-client, je ne comprends pas très bien pourquoi on les a separé dans une librairie à part ? Le but n'était justement pas de ne pas les shipper obligatoirement avec cozy-client ?

**Comment by kosssi** [comment]
Je ne crois pas, c'était surtout de montrer que c'était vraiment des librairies à part et que l'on peut utiliser facilement dans nos applications actuelles.

Tu vois un désavantage de les avoir dans un autre dépôt ? et de les instancier directement dans cozy-client ?

**Comment by ptbrowne** [comment]
> Tu vois un désavantage de les avoir dans un autre dépôt ?

Oui. Nouveau dépôt = possibilité de drift entre les librairies, + de difficulté à naviguer dans le code, moins facile de faire des changements qui impliquent les deux librairies. Après ya des avantages aussi, ca permet de bien découpler les fonctionnalités / *concerns* et faire en sorte qu'on ait des modules simples.

> et que l'on peut utiliser facilement dans nos applications actuelles.

+1

> et de les instancier directement dans cozy-client ?

Oui je vois que soudain, une librairie a une dépendance envers une autre alors qu'avant yavait pas de dépendance explicite. Je vois aussi que c'est moins flexible parce qu'on peut pas rajouter un nouveau plugin sans toucher à cozy-client, il faut aller changer le code de cozy-client pour intégrer le plugin.

Je pencherais plutôt vers l'architecture en plugin (+ *simple*, moins de choses liées entre elles, mais moins *facile* vu qu'il faut importer un plugin dans l'application et l'instancier [Simple vs Easy][1]). J'aimerais savoir ce que les autres en pensent.

[1]: https://www.youtube.com/watch?v=34_L7t7fD_U

**Comment by y-lohse** [comment]
Faire l'initialisation automatique veux aussi dire qu'il faut ajouter realtime et intents en dépendance a cozy-client, même si on ne les utilise pas. Ce sont des petites libs, mais ca reste dommage. Je favorise aussi l'approche par déclaration de plugin explicite.

Sur la forme de l'API je pense que `client.registerPlugin(new Intent())` est très bien — ca permet de faire l'ajout du plugin a un moment arbitraire, plutôt que de le forcer lors de l'init de cozy-client.

**Comment by drazik** [comment]
Je ne pense pas que cozy-client doive instancier les intents et/ou le realtime lui-même : parfois on n'en aura pas besoin; ça lie beaucoup les packages entre eux; c'est trop magique.

Un système de plugins qu'on passe à la création du client me parait bien plus clean. L'exemple d'utilisation de @CPatchane me parait top. Derrière, si les plugins ont une API commune d'initialisation (il me semble qu'ils ont besoin de l'URL de l'instance et d'un token), alors il n'y a plus rien de magique, et ces packages ne sont absolument pas correlés à cozy-client.

cozy-client appelerait une méthode `init` en passant l'URL et le token à la création; et une méthode `reset` sur chaque plugin lorsqu'on `reset` le client lui-même (comme pour les links, quoi).

Par contre, je verrais plutôt un objet `{ pluginName: Plugin }` pour l'initialisation : 

```js
import CozyClient from 'cozy-client'
import Realtime from 'cozy-realtime'
import { Intents } from 'cozy-interapp'

const client = new CozyClient({
   plugins: {
     realtime: new Realtime()
   }
}

client.registerPlugin('intents', new Intent())

// Utilisation : ajouter une clé intermédiaire `plugins` pour ne pas polluer le scope du client ?
client.plugins.intents.create(...)
```
