### ISSUE TITLE
[commitylint] Breaking change

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-libs#110]
With semantic release, breaking changes have to follow the format `BREAKING CHANGE: *subject*`. But our current configuration prevents us from using `BREAKING CHANGE` as a commit title :(

**Comment by ptbrowne** [comment]
Mmh are you sure ?

I think the BREAKING CHANGE mention must be in the *description*.

https://github.com/semantic-release/semantic-release#commit-message-format

> perf(pencil): remove graphiteWidth option
> 
> BREAKING CHANGE: The graphiteWidth option has been removed.
The default graphite width of 10mm is always used for performance reasons.

**Comment by y-lohse** [comment]
Aaah I think you're correct and I misread. Now I have some commit titles to fix!
