### ISSUE TITLE
Non-escaped characters in login when saving files creating sub-folders

### ISSUE THREAD

**Issue by RemiPail** [cozy/cozy-libs#1192]
Hi Cozy team,

I am developing a konnector to save files from another drive service (Reconnect) into my Cozy Drive. For that, I use the saveFiles function. 
I noticed that the files are stored in Administrative/konnector-name/konnector-login but in my case, the konnector-login contains "/" characters and so the files are stored in sub-folders. For example : Adminitrative/konnector-name/login-part1/login-part2/... 

**For example :**
Here is my login page for my konnector
![image](https://user-images.githubusercontent.com/63208886/102490224-d2ac0080-406e-11eb-9b99-fee31759c96b.png)

The connection succeeded
![image](https://user-images.githubusercontent.com/63208886/102491258-371b8f80-4070-11eb-96c4-e3b6d60a9253.png)

But my files are stored in a sub-folder like this :

```
Drive
  └─ Administrative
          └─ Reconnect
                  └─ julien.pilote.01
                          └─ 01
                                  └─ 1975
                                          └─ myfiles 
```

I think that "/" characters in the user login should be escaped when saving files in the Cozy Drive in order to looklike this :

```
Drive
  └─ Administrative
          └─ Reconnect
                  └─ julien.pilote.01/01/1975
                          └─  myfiles 
```

**Comment by ptbrowne** [comment]
Thanks for the issue and sorry for the delay. 

@doubleface, do you think it is a problem of cozy-konnector-libs ?

**Comment by Crash--** [comment]
It'll be an issue for cozy-stack (server) to have folder name containing `/` character since folders can be synched locally on the OS using cozy-desktop. The result is that `/` is currently a forbidden character. 

Maybe the solution is to convert these "/" to "-" or something?

**Comment by doubleface** [comment]
Since harvest creates this folder, harvest should escape the / char to avoid this problem I suppose

**Comment by ptbrowne** [comment]
Ah yes OK 👍
