### ISSUE TITLE
eslint-loader 2.1.1 does not get eslint-plugin-react as a dependency

### ISSUE THREAD

**Issue by gregorylegarec** [cozy/cozy-libs#131]
On cozy-home, using eslint-loader 2.1.1 does not add eslint-plugin-react to `node_modules` directory.

Version 2.1.0 does.

**Comment by ptbrowne** [comment]
I do not understand this issue ? What is the problem ?

BTW, I tried in a new repo to install eslint-loader@2.1.0 and eslint-loader@2.1.1 and neither installation installed eslint-plugin-react.

**Comment by gregorylegarec** [comment]
Honestly I don't remember and did not have problem since the opening of this issue.

Sorry for the disagreement and thanks to have take a look.
