### ISSUE TITLE
Too many props are propagated into the `Share` button

### ISSUE THREAD

**Issue by Ldoppea** [cozy/cozy-libs#1334]
When the `Share` button is displayed, this warning appears in the dev console:
![image](https://user-images.githubusercontent.com/1884255/128735130-11d4cc91-d103-4aff-bdf9-5bab4c247b1a.png)

This is due to `t` and `f` translation props (generated by I18n library) that are propagated until the final HTML `<button>` element (on `cozy-ui` side) by using rest operator for props (`{...rest}`) in all nested components

Code: 
https://github.com/cozy/cozy-libs/blob/9f463ef252b688ea412377fc782ed3df5c898e99/packages/cozy-sharing/src/ShareButton.jsx#L13-L43

**Comment by Merkur39** [comment]
Fix with https://github.com/cozy/cozy-libs/pull/1404
