### ISSUE TITLE
[realtime] Handle thrown error with onErrorCallback

### ISSUE THREAD

**Issue by gregorylegarec** [cozy/cozy-libs#146]
The error thrown here https://github.com/cozy/cozy-libs/blob/master/packages/cozy-realtime/src/index.js#L207 cannot be properly handled by an external code and will end in the console.

We should provide a way to catch it. Passing a `onError` handler to `getCozySocket()` could be the right thing to do. Then instead of throwing, we could just call `onError(realtimeError)`.

This fix need tests.

Thanks @nono for pointing this out.

**Comment by edas** [comment]
Closing. We have rewritten Realtime since then.
