### ISSUE TITLE
[all] Add a global .eslintrc using `cozy-app`

### ISSUE THREAD

**Issue by CPatchane** [cozy/cozy-libs#15]
No need to have one per package.

**Comment by kosssi** [comment]
@CPatchane but we have some difference:
- `cozy-device-helper` use `cozy-app/react`
- `realtime` use `cozy-app`

It's not a problem?

**Comment by CPatchane** [comment]
Hum, normally the `cozy-app/react` should exactly be the same as `cozy-app` but with `react` in plus. Let's try!
