### ISSUE TITLE
[publish] Terminer la migration

### ISSUE THREAD

**Issue by kosssi** [cozy/cozy-libs#20]
Il reste 2 tâches pour finaliser correctement la migration de `cozy-app-publish`:
- importer les _issues_ et les _PR_
- supprimer le dépôt https://github.com/cozy/cozy-app-publish

**Comment by ptbrowne** [comment]
J'ai importé les issues via https://github.com/IQAndreas/github-issues-import.

#66
#67
#68
#69
#70
#71
#72
#73
#74

**Comment by y-lohse** [comment]
Et le précédent repo est archivé — je pense que l'on peut fermer cette issue ?
