### ISSUE TITLE
cozy-realtime: add `_type` attribute into listen document

### ISSUE THREAD

**Issue by JF-Cozy** [cozy/cozy-libs#2023]
lors de l'utilisation du realtime notamment via `useRealtime(client, {'io.cozy.files': {created: doc => {}}})`, le document retourné dans la méthode de l'event (ici created par exemple) ne contient pas l'attribut `_type`.

L'idée serait d'ajouter le _type (via payload.type) dans le message reçu https://github.com/cozy/cozy-libs/blob/master/packages/cozy-realtime/src/CozyRealtime.js#L458 et d'ajouter côté back le _type dans le doc.

A savoir que le doc, notamment le io.cozy.files, reçu via le realtime n'est potentiellement pas le même que que celui reçu via /files/ . Il ressemble au doc reçu via /data/io.cozy.files. Il y a cette problématique sur les doctypes qui n'ont pas une route spécifique sur la stack (genre contacts). A savoir qu'en passant par RealtimeQueries ça ajoute le _type logiquement https://github.com/cozy/cozy-client/blob/master/packages/cozy-client/src/RealTimeQueries.jsx#L39

**Comment by nono** [comment]
Côté stack, on renvoie le type de document dans les réponses du temps-réel dans un champ `type` qui se trouve à côté du `doc`. Cf https://docs.cozy.io/en/cozy-stack/realtime/. Si vous voulez mettre `_type` dans le document, le mieux serait que cozy-realtime s'occupe de faire ça.

**Comment by JF-Cozy** [comment]
Pour la partie Realtime, voir https://github.com/cozy/cozy-libs/pull/2048

Pour la partie Client, j'ai testé, on a bien le _type qui est ajouté
