### ISSUE TITLE
Cozy-Flags : React Provider

### ISSUE THREAD

**Issue by gregorylegarec** [cozy/cozy-libs#207]
As we speak yesterday, I would like to use our stack provided flags directly in Cozy-Flags.

In Cozy-Home we are using flags directly specified in cozy context, defined in the `cozy.yaml` file. It implies to fetch the context at startup.

To use it in Cozy-Flags, I am thinking about creating two HOC.

### ContextFlagsProvider
Take the cozy context as prop, and set the related flags in Cozy-Flags. Also, pass the method `flag()` in children context. Once the cozy context has been fetched by app the Provider is synchronous.

### withFlags()
Take the `flag()` method form React context and pass it as prop to component.

### Provider
```
  <ContextFlagsProvider flags={context.features}>
    <App />
  </ContextFlagProvider>
```
### Consumer
```
  const Todo = props => (
    props.flag('disruptive-todo') ? <ExperimentalTodo /> : <OldTodo />
  )

  export default withFlags(Todo)
```

What do you think ?

**Comment by ptbrowne** [comment]
I like the Provider and 
Two remarks : 

- the `ContextFlagsProvider` could be done via the `CozyProvider` in `cozy-client`.  Flags could be stored in the Redux store of `cozy-client`. This brings the second remark
- The `flags` props could simply the slice from the redux store instead of the function. It brings observability for free through the redux mechanisms. With the function form, observability would not work for free as the flag getter would likely stay the same even if a flag changes (`prevProps.flag === props.flag`).  

The example becomes:

```
  const Todo = props => (
    props.flags.disruptive-todo ? <ExperimentalTodo /> : <OldTodo />
  )

  export default withFlags(Todo)
```

**Comment by drazik** [comment]
Nice ideas :+1:.

Don't you think doing this flag provider in `CozyProvider` in cozy-client is coupling two unrelated things @ptbrowne? I don't really know what to think: it's great to have observability for free, but I don't see why this should be done in our data access layer :thinking:

**Comment by gregorylegarec** [comment]
The benefits of the redux store and observability could be huge. Thanks for your feedback.

I guess it implies to put flags logic directly into CozyClient. Are we ok with that or is there some kind of abstraction that allow us to use directly the Cozy Client redux store ?

**Comment by ptbrowne** [comment]
> but I don't see why this should be done in our data access layer

The code for flags is fairly small and to me as CozyClient is our primary mean to connect to the Cozy, it will lower the barrier to using flags, which I think is a good thing. Flags will be saved on the Cozy of the user so they will need to have a CozyClient ready.

> coupling two unrelated things ?

As the only impact to the CozyClient code would be a reducer I do not think things will be too much coupled.

We have already talked about a plugin system about this for intents, I think this could also serve the flags.

```
plugin = { reducer?, setup }
```

**Comment by gregorylegarec** [comment]
So if I understand well, a whole plugin mechanism is necessary to integrate into cozy client.

What about a couple simple Components first here in Cozy-Flags ?

**Comment by ptbrowne** [comment]
cozy-flags needs a configured `cozy-client` that is setup on user connection, reset on user deconnection. Plus it needs a redux store. So it is ncessary for the cozy-flags to have a logic : 

- `onLogin`
- `onLogout`
- `setupReduxStore`

This is a generic need for 

- intents (minus the redux store)
- realtime (minus the redux store)

With or without plugin mechanism, something similar will need to be done in each of this libs. A plugin mechanism is merely just a interface each plugin adheres to.

**Comment by gregorylegarec** [comment]
After discussing with @ptbrowne, for now we will call `flags.enableFlags` with the `context.features` object from `Cozy-Home`, and then use directly Cozy-Flags.

Next steps should be:
* Plugin mechanism in CozyClient
* CozyFlags plugin for CozyClient
