### ISSUE TITLE
[haverst] Dependencies 

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-libs#389]
I just take a look at the haverst dep, and something is something is bothering me. 

Currently, we have as dep : 
```
"dependencies": {
    "cozy-client": "6.19.0",
    "cozy-realtime": "1.2.8",
    "cozy-ui": "19.21.2",
    "final-form": "4.11.1",
    "lodash": "4.17.11",
    "react-final-form": "3.7.0",
    "react-markdown": "4.0.6",
    "react-proptypes": "1.0.0"
  },

```

If we consider `Harvest` as a lib, as it says in its README, we should have : 
- cozy-client : peerDep (the app using the libs should provide it) and devDep (to be able to dev on it) 
- cozy-realtime: peerDep / devDep 
- cozy-ui: peerDep and devDep 
- react-proptypes: devDep 

No?

**Comment by ptbrowne** [comment]
Yep.
