### ISSUE TITLE
Harvest: Use KonnectorJobError in apps

### ISSUE THREAD

**Issue by CPatchane** [cozy/cozy-libs#433]
We should use [this exported class](https://github.com/cozy/cozy-libs/blob/master/packages/cozy-harvest-lib/src/helpers/konnectors.js#L40) to handle konnector errors in applications.
We may need to add also a `isTwoFAError` method to handle those errors

**Comment by ptbrowne** [comment]
What kind of konnector error do we need to deal with in applications ?

**Comment by CPatchane** [comment]
I have this example from cozy-home https://github.com/cozy/cozy-home/blob/master/src/lib/konnectors.js#L50-L89, we could clearly rely on harvest for that

**Comment by ptbrowne** [comment]
Ah yes I see, thanks !

**Comment by CPatchane** [comment]
Closing it, feel free to open a new issue if needed.
