### ISSUE TITLE
Harvest: test withLocales

### ISSUE THREAD

**Issue by gregorylegarec** [cozy/cozy-libs#442]
In `index.js`, `withLocales` HOC is not tested, we should provide a test to ensure `lang` is actually injected into children components.

**Comment by ptbrowne** [comment]
Yannick recently moved implemented `withLocales` in cozy-ui. I think instead of doing a test here, it would be better to use cozy-ui's version and add a test there.

https://github.com/cozy/cozy-ui/blob/master/react/I18n/withLocales.jsx

**Comment by ptbrowne** [comment]
See https://github.com/cozy/cozy-ui/pull/978
