### ISSUE TITLE
[harvest] Handle folders manifest attribute

### ISSUE THREAD

**Issue by gregorylegarec** [cozy/cozy-libs#480]
Most recent konnectors are declaring a `folders` attribute [in their manifests](https://github.com/search?q=org%3Akonnectors+defaultDir&type=Code). This `folders` is not yet correctly handled by Harvest (but it is in Cozy-Home, see https://github.com/cozy/cozy-home/pull/1029).

**Comment by Crash--** [comment]
@y-lohse @doubleface Can I close this issue? We now handle it from harvest, right?

**Comment by y-lohse** [comment]
Yes we're good https://github.com/cozy/cozy-libs/blob/master/packages/cozy-harvest-lib/src/helpers/konnectors.js#L271
