### ISSUE TITLE
[publish] Manual script asynchronous publish call

### ISSUE THREAD

**Issue by gregorylegarec** [cozy/cozy-libs#51]
Issue encountered during https://github.com/cozy/cozy-libs/pull/50. Travis changes has not been done to Manual.

In Manual Script, publish call is made in a callback passed to `prompt.get()`, so it makes it impossible to test.

We should mutualize publication code between Travis and Manual scripts in the same module, and pass it as an argument to both `travis()` and `manual()` methods, so the whole process would be easily testable.

**Comment by ptbrowne** [comment]
I think we can close this issue ?
