### ISSUE TITLE
Realtime: Detect change during subscribe

### ISSUE THREAD

**Issue by gregorylegarec** [cozy/cozy-libs#518]
I have been facing an edge case yesterday with the realtime with konnector job.

To run a konnector job, we call the specific endpoint on cozy-stack to launch a trigger. This endpoint response contains the launched `io.cozy.jobs` document. Then we listen to the job on realtime to know if it succeeds or fails.

On my local environment, all my konnector job were failing with a specific error :
```
ERRO[17484] error while performing job: stat /Users/gregory/Dev/cozy/apps/cozy-home/storage/cozy.tools:8080/.cozy_konnectors/dummy/1.0.0-7605c48a12af6cf663dec6e92ee77385e308d488: no such file or directory  domain="cozy.tools:8080" job_id=199d8c81a3c796c588810ec3f704e66a nspace=jobs worker_id=konnector/7
```
This was due to the fact that I removed my `storage/cozy.tools:8080/*` after having installed the `dummy` konnector. It was failing really really fast after launch, and it was perfect for my tests. But on 50% of my tests, the job was running indefinitely without failing ever.

After investigating, I realized that the job was updated to an errored state *before* the realtime subscribed to the `io.cozy.jobs` document. So I was never knowing that the job had failed.

I fixed this with this PR : https://github.com/cozy/cozy-libs/pull/517

So, do you think we should implement this kind of behaviour directly into the realtime lib ?

For example right after a successful subscribe, we could fetch the related document and emit a `subscribed` event. It could work well with single document but not so well with doctypes.

**Comment by edas** [comment]
I don't think we should implement that in Realtime.
We know that we will miss some events. Realtime has no buffer so each network glitch may make us loose events. 

- If you want to make sure to catch events after an action, subscribe before you launch any actions.
- If you can, or if your code should absolutly never miss anything, implement a fallback with a manual fetch each time the Realtime (re)connect
