### ISSUE TITLE
(Cozy-Realtime): few errors

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-libs#573]
I just go back to a tab opened a few hours ago, and I had my console opened. 

I saw these errors, concerning the realtime : 
<img width="990" alt="Capture d’écran 2019-07-02 à 08 26 23" src="https://user-images.githubusercontent.com/1107936/60489034-aa2a1e00-9ca3-11e9-9a5b-eda6489b473a.png">

I didn't take the time to see how we can fix them.

cc @edas

**Comment by edas** [comment]
J'ai essayé de trouver cette dernière plusieurs fois, je n'ai pas réussi à la reproduire ni à trouver comment elle pourrait arriver même théoriquement. 
Cela dit le montage actuel du Realtime me parait très fragile. J'ai proposé une PR de réécriture, je ne sais pas trop quoi proposer de mieux en l'état

**Comment by edas** [comment]
We rewrote the realtime, so these errors are not here anymore.
