### ISSUE TITLE
[publish] Ajouter eslint-config-cozy-app

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-libs#67]
<a href="https://github.com/kosssi"><img src="https://avatars2.githubusercontent.com/u/1135513?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kosssi](https://github.com/kosssi)**
_Tuesday Apr 10, 2018 at 16:23 GMT_
_Originally opened as https://github.com/cozy/cozy-app-publish/issues/18_

----

**Comment by ptbrowne** [comment]
No mention of eslint-config-cozy-app here https://github.com/cozy/cozy-libs/blob/master/packages/cozy-app-publish/.eslintrc.json

**Comment by kosssi** [comment]
We can close this issue because eslint [is configured with `eslint-config-cozy-app`](https://github.com/cozy/cozy-libs/blob/master/.eslintrc) on main directory
