### ISSUE TITLE
cozy-doctypes: Connectors forced to include cozy-client to use cozy-doctypes

### ISSUE THREAD

**Issue by doubleface** [cozy/cozy-libs#688]
In https://github.com/cozy/cozy-libs/blob/9cb8a96afc9758dee884d7bd13d505227d640ac7/packages/cozy-doctypes/src/Document.js#L90 cozy-client is included only to know if cozy-client or cozy-client-js is used as client.

This forces connectors to include cozy-client to be able to use cozy-doctypes.

I think cozy-doctypes should use cozy-stack-client instead, to allow cozy-doctypes to be more widely used.

**Comment by Crash--** [comment]
We now use `cozy-doctypes` in our front app and we need to use cozy-client and not stack client to use the cache mechanism for instance. 

When we use the lib in 2 env, should we create 2 entry points?

**Comment by ptbrowne** [comment]
> This forces connectors to include cozy-client to be able to use cozy-doctypes.

> I think cozy-doctypes should use cozy-stack-client instead, to allow cozy-doctypes to be more widely used.

Are you worried about the size ?

**Comment by doubleface** [comment]
> Are you worried about the size ?

This is not my only concern, and I know we already have pdfjs which is far heavier than that. My other concern is that cozy-client is made for a browser environment, react dependency is clue for that and also the caching mecanism.

The existence of cozy-stack-client looked like a good way to make a separation between browser specific features and browser/nodejs compatible features.

**Comment by edas** [comment]
I do not agree. Consider that connectors will need the full cozy-client. You may not use the react layer or the pouchdb link but you may require future layers outside of cozy-stack-client.

Trying to load only the stack-client is a premature optimisation we may regret later.

**Comment by doubleface** [comment]
It is decided that cozy-client will also be used by connectors. This issue can be closed
