### ISSUE TITLE
feat: Add io.cozy.terms

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-libs#704]
io.cozy.terms are missing. Here is an example

```
{
    "_id": "550f42b42f1cc296b546d26d89e0ab4f",
    "_rev": "1-36bdcd74645a77c5436a9b232a7e07ea",
    "accepted": true,
    "acceptedAt": "2019-02-13T15:10:19.380Z",
    "termsId": "bi-terms",
    "url": "https://files.cozycloud.cc/CGU_Budgea_Bank_Agent_2018-08-29.pdf",
    "version": "budgea-002"
  }
```

**Comment by edas** [comment]
What do you mean?
Where do you want that to be added?

Documentation is already there in https://github.com/cozy/cozy-doctypes/blob/master/docs/io.cozy.terms.md

**Comment by ptbrowne** [comment]
Oups je me suis trompé de repo. De toute facon je ferme l'issue, les io.cozy.terms n'étaient seulement pas dans la table des matières. C'est corrigé https://github.com/cozy/cozy-doctypes/commit/51ac4d63ce24915bc025f7dc434b88bca3283a28
