### ISSUE TITLE
[publish] Merging beta and stable targets

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-libs#71]
<a href="https://github.com/y-lohse"><img src="https://avatars2.githubusercontent.com/u/2261445?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [y-lohse](https://github.com/y-lohse)**
_Thursday Aug 02, 2018 at 13:02 GMT_
_Originally opened as https://github.com/cozy/cozy-app-publish/issues/57_

----

Right now when publishing a stable version, we merge the stable and beta targets in the hooks (so that an instance marked as beta target also gets the stable update).

Should we change this?

I personally think so. If that's really the behavior someone wants, they can just specify the same instance in both targets, and it's explicit. The current behavior relies on an implicit rule that is sensible, but still surprising.

cc @gregorylegarec @CPatchane

**Comment by ptbrowne** [comment]
<a href="https://github.com/CPatchane"><img src="https://avatars2.githubusercontent.com/u/10224453?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CPatchane](https://github.com/CPatchane)**
_Thursday Aug 02, 2018 at 14:00 GMT_

----

Seems legit, since it's easy to get this behaviour, there is no interest to put it as default without a way to avoid it 👍

**Comment by ptbrowne** [comment]
<a href="https://github.com/gregorylegarec"><img src="https://avatars3.githubusercontent.com/u/776764?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gregorylegarec](https://github.com/gregorylegarec)**
_Friday Aug 03, 2018 at 15:22 GMT_

----

Sorry I missed this issue and directly made #59.

**Comment by ptbrowne** [comment]
Is this issue still relevant ?

**Comment by gregorylegarec** [comment]
@ptbrowne Absolutely not, TARGETS_BETA and TARGETS_STABLE variables are deprecated.
