### ISSUE TITLE
[publish] Do not merge TARGETS_BETA in TARGETS_STABLE anymore

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-libs#73]
<a href="https://github.com/gregorylegarec"><img src="https://avatars3.githubusercontent.com/u/776764?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gregorylegarec](https://github.com/gregorylegarec)**
_Friday Aug 03, 2018 at 14:58 GMT_
_Originally opened as https://github.com/cozy/cozy-app-publish/pull/59_

----

Eventually it appears that it is not a so good idea to merge cozy instances specified in the environment variable `TARGETS_BETA` into `TARGETS_STABLE`.

It this feature is still needed, it seems better to do in `travis.yml`: 

```yml
- global:
  - TARGETS_BETA=myinstance.cozy.rocks
  - TARGETS_STABLE=myinstance.cozy.rocks
```
In this way, `myinstance.cozy.rocks` will be updated both with beta and stable versions.

Update: see #57, thanks @y-lohse to have pointed it to me.

----

_**[gregorylegarec](https://github.com/gregorylegarec)** included the following code: https://github.com/cozy/cozy-app-publish/pull/59/commits_

**Comment by gregorylegarec** [comment]
Totally agree. 👍

**Comment by y-lohse** [comment]
Duplicate of https://github.com/cozy/cozy-libs/issues/71
