### ISSUE TITLE
feat: Use directly stack client methods

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-libs#823]
More and more methods move to cozyStackClient, we could use them directly
to slim down cozy-doctypes.

See https://github.com/cozy/cozy-client/pull/530

**Comment by edas** [comment]
And probably move the public API to cozy-client instead of cozy-stack-client

**Comment by ptbrowne** [comment]
I'd be happy to discuss this but since the collection() method is already on cozy-client, the public API is already on cozy-client ?
