### ISSUE TITLE
Scoped history for modules exposed via routes

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-libs#832]
Some of our libs (harvest, procedures) come with routes that need to be inserted
in the routes of the application. When coding navigation in
those components, we use relative path so that component need
not be aware of the route mount point of the module.

An alternative would be to pass a `history` proxy that would
be aware of this mount point so that something like

```
history.push('<cozy-harvest>/route/inside/harvest')
```

be possible inside harvest.

More context on initial discussion : https://github.com/cozy/cozy-libs/pull/830#discussion_r333624813, also here https://github.com/cozy/cozy-libs/pull/840#discussion_r336412593

**Comment by Crash--** [comment]
I think we have done the work on harvest. Procedures is in stand by atm, should we close this issue?

**Comment by ptbrowne** [comment]
OK for me, thanks for reminding me :)
