### ISSUE TITLE
[all] Handle global or individual changelog file(s)

### ISSUE THREAD

**Issue by CPatchane** [cozy/cozy-libs#99]
It's very useful to have them when renovate push a new update on repositories

**Comment by CPatchane** [comment]
Up!
Renovate seems to base on a changelog.md file at the root of the repository, we may have to create and handle one here.
Some links [here](
https://github.com/renovatebot/renovate/issues/2162#issuecomment-399635982) and [here](
https://github.com/renovatebot/renovate/issues/2926)

We can also use the PR based [Lerna Changelog](https://github.com/lerna/lerna-changelog) to handle changelog computing like I used to do for [CCA](https://github.com/CPatchane/create-cozy-app/blob/master/lerna.json#L6-L14) since the CCA updates work well with Renovate still now.

**Comment by y-lohse** [comment]
It's not clear what we're waiting for here. Is there any concrete action that needs to be taken, or a question that needs an answer?

Personally I think it would be cool to have changelogs for the individual packages, but one global changelog would be too noisy to be useful.
I'm not sure how to best do that, I can't find much on the renovate docs on this subject, but I think it's possible.

**Comment by ptbrowne** [comment]
There are now github releases thanks to https://github.com/cozy/cozy-libs/commit/f7669e5d3f37f88e416219666f022c81d3bb4b3a but still not sign of changelog in renovate prs.. I don't know what's missing (PR for harvest lib update https://github.com/cozy/cozy-home/pull/1246, see release notes on https://github.com/cozy/cozy-libs/releases.

**Comment by CPatchane** [comment]
Closing it, feel free to open a new issue if needed.
